### ISSUE TITLE
Old urls in doc

### ISSUE THREAD

**Issue by okamara** [zebrunner/community-edition#511]
Steps:
1. Open https://zebrunner.github.io/community-edition/
- Zebrunner Reporting url is invalid -> https://zebrunner.github.io/zebrunner/ 
- Repo url need update on the page https://zebrunner.github.io/community-edition/config-guide/
<img width="733" alt="Снимок экрана 2022-02-02 в 14 39 02" src="https://user-images.githubusercontent.com/32964663/152171942-57964232-c46a-444f-9c3d-277579a40133.png">

<img width="710" alt="Снимок экрана 2022-02-02 в 14 03 25" src="https://user-images.githubusercontent.com/32964663/152172409-0eecf6bd-b986-4f4d-b022-8e1e7821bd41.png">

**Comment by vdelendik** [comment]
Some major refactoring done on documentation to made it simpler... Mostly moved optional steps into the Integration module.
Also in scope of fixes for this particular ticket
1. removed links onto the docker pull stats as it refered to old qaprosoft docker organization and not up-to-date. Current implementation has much more micro-services that's why we don't plan to show this stat anymore
![image](https://user-images.githubusercontent.com/4551455/153755952-8f38f211-9af1-4b1a-ba62-b8fd9701401b.png)
2. fixed link to `Zebrunner Reporting` referring to our cloud https://zebrunner.com/
3. won't fix repoUrl on screenshot as qaprosoft has valid redirection to zebrunner org on github

**Comment by okamara** [comment]
Verified, fixed.
